import type { Metadata } from 'next';
import './globals.css';
import '@/stylesheets/commonClasses.css';
import '@/stylesheets/layout.css';
import LayoutProvider from '@/components/LayoutProvider';
<link
  href='https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css'
  rel='stylesheet'
/>;
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <LayoutProvider>{children}</LayoutProvider>;
}
