import type { Metadata } from 'next';
import './globals.css';
import '@/stylesheets/commonClasses.css';

import LayoutProvider from '@/components/LayoutProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <LayoutProvider>{children}</LayoutProvider>;
}
